version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    working_dir: /app
    command: uvicorn --app-dir src main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8000:80"  # host:container
    env_file:
      - ./backend/.env.local.container
    environment:
      LOG_LEVEL: INFO
      PYTHONPATH: /app/src  # domain.* 用
    volumes:
      - ./backend/src:/app/src:rw,delegated
    # 開発速度重視: 依存が変わったらコンテナ再ビルド
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env.local.container
    environment:
      PORT: 80
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:rw,delegated
      - frontend_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  backend_venv: {}
  frontend_node_modules: {}

networks: {}
