// AUTO-GENERATED BY `npm run gen:api`.
// 初回はまだ生成していないため一時的な型エイリアスを定義。
// コマンド実行後、この内容は openapi-typescript により上書きされます。

// Backend の Todo モデルに合わせた暫定型 (生成後削除される想定)
export interface components {
  schemas: {
    Todo: {
      id: string;
      title: string;
      description?: string | null;
      priority: 'low' | 'normal' | 'high' | 'urgent';
      dueDate?: string | null;
      tags?: string[] | null;
      completed: boolean;
      createdAt: string;
      updatedAt: string;
    };
  };
}

export type Todo = components['schemas']['Todo'];
