from __future__ import annotations
from typing import Protocol, List, Optional
from domain.models.todo import Todo

class TodoRepository(Protocol):
    def add(self, todo: Todo) -> Todo: ...
    def list(self) -> List[Todo]: ...
    def get(self, todo_id: str) -> Optional[Todo]: ...
    def save(self, todo: Todo) -> Todo: ...
    def delete(self, todo_id: str) -> bool: ...
