name: Backend Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'infra/**'
      - '.github/workflows/backend-deploy.yml'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

concurrency:
  group: backend-deploy-${{ github.ref_name }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.12'
  ACR_NAME: ${{ vars.ACR_NAME }}
  RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  BACKEND_IMAGE_REPO: backend
  # 単一環境用。リポジトリ変数 BACKEND_APP_NAME を 1 つだけ定義してください。
  BACKEND_APP_NAME: ${{ vars.BACKEND_APP_NAME }}
  # イメージタグはコミット SHA のみ（単一環境・手動タグ不要）
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install backend deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: backend
        run: pytest -q

  build-deploy:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Build Backend Image
        run: |
          docker build -f backend/Dockerfile -t $ACR_NAME.azurecr.io/$BACKEND_IMAGE_REPO:$IMAGE_TAG ./backend

      - name: Push Image
        run: docker push $ACR_NAME.azurecr.io/$BACKEND_IMAGE_REPO:$IMAGE_TAG

      - name: Deploy / Update Container App
        run: |
          az containerapp update \
            --name $BACKEND_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_NAME.azurecr.io/$BACKEND_IMAGE_REPO:$IMAGE_TAG

      - name: Output Image Ref
        run: echo "IMAGE=$ACR_NAME.azurecr.io/$BACKEND_IMAGE_REPO:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Summary
        run: |
          echo "Deployed $BACKEND_APP_NAME with image tag $IMAGE_TAG" >> $GITHUB_STEP_SUMMARY